### ISSUE TITLE
Comandos set

### ISSUE THREAD

**Issue by duhow** [gentakojima/profesoroakdocs#1]
- **admin_chat** [Chat ID], enviar mensajes administrativos al Chat ID especificado. Tener en cuenta que si el grupo admin se convierte en supergrupo, el Chat ID cambiará, y se debe reajustar este parámetro de nuevo.
- **announce_welcome** [ON/OFF], para que el Oak salude a los nuevos usuarios que entren.
- **team_exclusive** [B/R/Y], para configurar que el grupo es exclusivo de un color (grupo Azul/Rojo/Amarillo).
- **team_exclusive_kick** [ON/OFF], si entra un usuario de otro color será expulsado.
- **limit_join** [ON/OFF], cualquier usuario nuevo que entre será baneado (no se permite la entrada de usuarios nuevos). Se cambiará a ban temporal en un futuro.
- **location** [44.4444,2.222], poner las coordenadas del centro de la ciudad/grupo. Aún no hay uso para esto, pero está pensado para invitar a usuarios cercanos a la ubicación, enviar Raids / Pokémon avistados...
- **location_radius** [1000], metros del radio de alcance de la ubicación.
- **mute_content**, aplicar mediante el comando **Mutear contenido**.
- **russian_roulette_easy** [ON/OFF], si es "fácil" el Oak no baneará si alguien muere.
- **antiflood** [2-10], cantidad de "puntos" que se deben alcanzar antes de kickear a alguien por flood de imágenes / stickers / media.
- **antiflood_ban** [ON/OFF], en vez de kick, hará ban.
- **abandon** [ON/OFF], cada vez que alguien hable, el Oak dirá que el grupo está abandonado. (A ver si con un poco de suerte la gente lee el p### anclado...)
- **antispam** [ON/OFF], por defecto siempre estará activo. Si el grupo no le interesa, puede desactivarlo.
- **antiafk** [5-60], si la persona entra y en **X** minutos no habla, se le echará del grupo.
- **require_avatar** [ON/OFF], los usuarios nuevos deberán tener foto de perfil. **DESACTIVADO**.
- **require_verified** [ON/OFF], si el usuario no está validado, le dirá un mensaje de "para estar en este grupo debes estar validado."
- **require_verified_kick** [ON/OFF], directamente no dirá na, kick y punto.
- **jokes** [ON/OFF], hacer las "bromas" en el grupo.
- **play_games** [ON/OFF], jugar a juegos en el grupo (botella, dados, ruleta...)
- **offtopic_chat** [link], link del grupo Offtopic si hay.
- **link_chat** [ID], @NombreDelGrupo o si es "t.me/joinchat/", borrar esa parte de la URL y quedarse únicamente con la del final. Cada vez que alguien pida el "link del grupo" devuelve esto.

**Comment by gentakojima** [comment]
Muchas gracias, David. Iré incorporando todo esto en cuanto pueda.

**Comment by fpalaciost** [comment]
- **disable_nest_log** [ON/OFF], no recibir alertas de los usuarios que piden nidos
